
// This file has been generated by the GUI designer. Do not modify.
namespace AppProject
{
	public partial class WindowMijenjajKorisnika
	{
		private global::Gtk.EventBox eventboxMijenjajKorisnika;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AppProject.WindowMijenjajKorisnika
			this.Name = "AppProject.WindowMijenjajKorisnika";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowMijenjajKorisnika");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AppProject.WindowMijenjajKorisnika.Gtk.Container+ContainerChild
			this.eventboxMijenjajKorisnika = new global::Gtk.EventBox();
			this.eventboxMijenjajKorisnika.Name = "eventboxMijenjajKorisnika";
			this.Add(this.eventboxMijenjajKorisnika);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
