
// This file has been generated by the GUI designer. Do not modify.
namespace AppProject
{
	public partial class WindowMijenjajAktivnost
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AppProject.WindowMijenjajAktivnost
			this.Name = "AppProject.WindowMijenjajAktivnost";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowMijenjajAktivnost");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
