
// This file has been generated by the GUI designer. Do not modify.
namespace AppProject
{
	public partial class WindowDodajAktivnost
	{
		private global::Gtk.EventBox eventboxDodajAktivnost;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label labelDatum;

		private global::Gtk.ComboBox comboboxDan;

		private global::Gtk.ComboBox comboboxMjesec;

		private global::Gtk.ComboBox comboboxGodina;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Calendar calendarAktivnosti;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label labelNaziv;

		private global::Gtk.Entry entry4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label labelTip;

		private global::Gtk.ComboBox comboboxTipovi;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label labelVrijeme;

		private global::Gtk.SpinButton spinbutton1;

		private global::Gtk.SpinButton spinbutton2;

		private global::Gtk.SpinButton spinbutton3;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label7;

		private global::Gtk.Label labelJedinicaMjere;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button buttonSpremi;

		private global::Gtk.Button buttonOdustani;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AppProject.WindowDodajAktivnost
			this.Name = "AppProject.WindowDodajAktivnost";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowDodajAktivnost");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AppProject.WindowDodajAktivnost.Gtk.Container+ContainerChild
			this.eventboxDodajAktivnost = new global::Gtk.EventBox();
			this.eventboxDodajAktivnost.Name = "eventboxDodajAktivnost";
			// Container child eventboxDodajAktivnost.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelDatum = new global::Gtk.Label();
			this.labelDatum.Name = "labelDatum";
			this.labelDatum.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
			this.hbox2.Add(this.labelDatum);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.labelDatum]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboboxDan = global::Gtk.ComboBox.NewText();
			this.comboboxDan.Name = "comboboxDan";
			this.hbox2.Add(this.comboboxDan);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboboxDan]));
			w2.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboboxMjesec = global::Gtk.ComboBox.NewText();
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("sječanj"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("veljača"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("ožujak"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("travanj"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("svibanj"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("lipanj"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("srpanj"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("kolovoz"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("rujan"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("listopad"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("studeni"));
			this.comboboxMjesec.AppendText(global::Mono.Unix.Catalog.GetString("prosinac"));
			this.comboboxMjesec.Name = "comboboxMjesec";
			this.hbox2.Add(this.comboboxMjesec);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboboxMjesec]));
			w3.Position = 2;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboboxGodina = global::Gtk.ComboBox.NewText();
			this.comboboxGodina.Name = "comboboxGodina";
			this.hbox2.Add(this.comboboxGodina);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboboxGodina]));
			w4.Position = 3;
			this.vbox5.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.calendarAktivnosti = new global::Gtk.Calendar();
			this.calendarAktivnosti.CanFocus = true;
			this.calendarAktivnosti.Name = "calendarAktivnosti";
			this.calendarAktivnosti.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox1.Add(this.calendarAktivnosti);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.calendarAktivnosti]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w8.Position = 2;
			this.vbox5.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelNaziv = new global::Gtk.Label();
			this.labelNaziv.Name = "labelNaziv";
			this.labelNaziv.LabelProp = global::Mono.Unix.Catalog.GetString("Naziv aktivnosti:");
			this.hbox6.Add(this.labelNaziv);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelNaziv]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.hbox6.Add(this.entry4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entry4]));
			w11.Position = 1;
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelTip = new global::Gtk.Label();
			this.labelTip.Name = "labelTip";
			this.labelTip.LabelProp = global::Mono.Unix.Catalog.GetString("Tip aktivnosti:");
			this.hbox7.Add(this.labelTip);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.labelTip]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxTipovi = global::Gtk.ComboBox.NewText();
			this.comboboxTipovi.Name = "comboboxTipovi";
			this.hbox7.Add(this.comboboxTipovi);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxTipovi]));
			w14.Position = 1;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelVrijeme = new global::Gtk.Label();
			this.labelVrijeme.Name = "labelVrijeme";
			this.labelVrijeme.LabelProp = global::Mono.Unix.Catalog.GetString("Vrijeme:");
			this.hbox8.Add(this.labelVrijeme);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.labelVrijeme]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.spinbutton1 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10D;
			this.spinbutton1.ClimbRate = 1D;
			this.spinbutton1.Numeric = true;
			this.hbox8.Add(this.spinbutton1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.spinbutton1]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.spinbutton2 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbutton2.CanFocus = true;
			this.spinbutton2.Name = "spinbutton2";
			this.spinbutton2.Adjustment.PageIncrement = 10D;
			this.spinbutton2.ClimbRate = 1D;
			this.spinbutton2.Numeric = true;
			this.hbox8.Add(this.spinbutton2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.spinbutton2]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.spinbutton3 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbutton3.CanFocus = true;
			this.spinbutton3.Name = "spinbutton3";
			this.spinbutton3.Adjustment.PageIncrement = 10D;
			this.spinbutton3.ClimbRate = 1D;
			this.spinbutton3.Numeric = true;
			this.hbox8.Add(this.spinbutton3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.spinbutton3]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox5.Add(this.hbox8);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Jedinica:");
			this.hbox9.Add(this.label7);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label7]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.labelJedinicaMjere = new global::Gtk.Label();
			this.labelJedinicaMjere.Name = "labelJedinicaMjere";
			this.hbox9.Add(this.labelJedinicaMjere);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.labelJedinicaMjere]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox5.Add(this.hbox9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
			w23.Position = 5;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonSpremi = new global::Gtk.Button();
			this.buttonSpremi.CanFocus = true;
			this.buttonSpremi.Name = "buttonSpremi";
			this.buttonSpremi.UseUnderline = true;
			this.buttonSpremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox10.Add(this.buttonSpremi);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonSpremi]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox10.Add(this.buttonOdustani);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonOdustani]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox5.Add(this.hbox10);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox10]));
			w26.Position = 6;
			w26.Expand = false;
			w26.Fill = false;
			this.eventboxDodajAktivnost.Add(this.vbox5);
			this.Add(this.eventboxDodajAktivnost);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 561;
			this.DefaultHeight = 452;
			this.Show();
			this.calendarAktivnosti.PrevMonth += new global::System.EventHandler(this.UpdateDate);
			this.calendarAktivnosti.PrevYear += new global::System.EventHandler(this.UpdateDate);
			this.calendarAktivnosti.NextYear += new global::System.EventHandler(this.UpdateDate);
			this.calendarAktivnosti.MonthChanged += new global::System.EventHandler(this.UpdateDate);
			this.calendarAktivnosti.DaySelected += new global::System.EventHandler(this.UpdateDate);
			this.calendarAktivnosti.NextMonth += new global::System.EventHandler(this.UpdateDate);
			this.comboboxTipovi.Changed += new global::System.EventHandler(this.JedinicaMjere);
			this.buttonOdustani.Clicked += new global::System.EventHandler(this.OdustaniClicked);
		}
	}
}
