
// This file has been generated by the GUI designer. Do not modify.
namespace AppProject
{
	public partial class WindowDodajAktivnost
	{
		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label labelDatum;

		private global::Gtk.Entry entry1;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label labelNaziv;

		private global::Gtk.Entry entry4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label labelTip;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label labelVrijeme;

		private global::Gtk.Entry entry3;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label7;

		private global::Gtk.Entry entry2;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button buttonSpremi;

		private global::Gtk.Button buttonOdustani;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Calendar calendar1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AppProject.WindowDodajAktivnost
			this.Name = "AppProject.WindowDodajAktivnost";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowDodajAktivnost");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AppProject.WindowDodajAktivnost.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelDatum = new global::Gtk.Label();
			this.labelDatum.Name = "labelDatum";
			this.labelDatum.LabelProp = global::Mono.Unix.Catalog.GetString("Datum:");
			this.hbox5.Add(this.labelDatum);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.labelDatum]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox5.Add(this.entry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry1]));
			w2.Position = 1;
			this.vbox5.Add(this.hbox5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.labelNaziv = new global::Gtk.Label();
			this.labelNaziv.Name = "labelNaziv";
			this.labelNaziv.LabelProp = global::Mono.Unix.Catalog.GetString("Naziv aktivnosti:");
			this.hbox6.Add(this.labelNaziv);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.labelNaziv]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.hbox6.Add(this.entry4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entry4]));
			w5.Position = 1;
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelTip = new global::Gtk.Label();
			this.labelTip.Name = "labelTip";
			this.labelTip.LabelProp = global::Mono.Unix.Catalog.GetString("Tip aktivnosti:");
			this.hbox7.Add(this.labelTip);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.labelTip]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.Name = "comboboxentry1";
			this.hbox7.Add(this.comboboxentry1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.comboboxentry1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelVrijeme = new global::Gtk.Label();
			this.labelVrijeme.Name = "labelVrijeme";
			this.labelVrijeme.LabelProp = global::Mono.Unix.Catalog.GetString("Vrijeme:");
			this.hbox8.Add(this.labelVrijeme);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.labelVrijeme]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hbox8.Add(this.entry3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry3]));
			w11.Position = 1;
			this.vbox5.Add(this.hbox8);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Jedinica:");
			this.hbox9.Add(this.label7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label7]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.Text = global::Mono.Unix.Catalog.GetString("npr. 15 kilometara");
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.hbox9.Add(this.entry2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entry2]));
			w14.Position = 1;
			this.vbox5.Add(this.hbox9);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonSpremi = new global::Gtk.Button();
			this.buttonSpremi.CanFocus = true;
			this.buttonSpremi.Name = "buttonSpremi";
			this.buttonSpremi.UseUnderline = true;
			this.buttonSpremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox10.Add(this.buttonSpremi);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonSpremi]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonOdustani = new global::Gtk.Button();
			this.buttonOdustani.CanFocus = true;
			this.buttonOdustani.Name = "buttonOdustani";
			this.buttonOdustani.UseUnderline = true;
			this.buttonOdustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox10.Add(this.buttonOdustani);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonOdustani]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox5.Add(this.hbox10);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox10]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox4.Add(this.vbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox5]));
			w19.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox4.Add(this.calendar1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.calendar1]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox4.Add(this.vbox4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox4]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.Add(this.hbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 490;
			this.DefaultHeight = 369;
			this.Show();
		}
	}
}
