
// This file has been generated by the GUI designer. Do not modify.
namespace AppProject
{
	public partial class WindowDodajTip
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AppProject.WindowDodajTip
			this.Name = "AppProject.WindowDodajTip";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowDodajTip");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
